//Contains all the Strings for different languages. New languages can be added here
module.exports = {
    en: {
        translation: {
            WELCOME_MSG: 'Welcome to the My Thai Star App. What can I do for you?',
            REQUEST_DISH_MSG: 'Your requested dish is ',
            PRICE_MSG: 'The price for ',
            IS_MSG: ' is ',
            EUROS_MSG: ' Euros',
            STATUS_MSG: 'The status of the Order ',
            SUCCESS_MSG: ' has succesfully been changed to ',
            BOOKING_MSG: 'Your table has been succesfully booked.',
            ERROR_BOOKING_MSG: 'There has been an error. Please make sure that the data of oyur order is correct. You may try again.',
            ORDER_SUCCESS_MSG: 'Your order has been sent to the restaurant',
            NO_MSG: 'no',
            YES_MSG: 'yes',
            THANK_MSG: 'Ok. Thank you for your booking',
            HELP_MSG: 'You can ask me what dishes we have or how much they cost, book a table or order food! How can I help?',
            GOODBYE_MSG: 'Goodbye!',
            ERR_MSG: 'Sorry, I don\'t know about that. Please try again.',
            REFLECT_MSG: 'You just triggered {{intent}}',
            PROBLEM_MSG: 'Sorry, I had trouble doing what you asked. Please try again.',
            ADD_DISH_MSG: 'If you want to add something to your order say "yes". Otherwise say "send order"',
            THANK_ORDER_MSG: 'Thank you for your order',
            DISHES_MSG: 'The available dishes are: ',
            BVG_MSG: 'The available beverages are: ',
            INHOUSE_ACTIVATED_MSG: 'The inhouse mode has been activated.',
            DELIVERY_MSG: 'Would you like to eat in the restaurant or get your meal delivered?',
            DELIVERY_CHOSEN_MSG: 'Your delivery option has been saved. To finish your order say "send order".',
            BEVERAGE_MSG: 'The chosen beverage has been added to your order.',
            ID_SET_MSG: 'The table ID has been set to ',
            EXTRAS_MSG: 'You can choose between the following extras: ', 
            ADD_EXTRA_MSG: ' with extra ',
            CART_MSG: 'Your order contains ',
            CART_DELETED_MSG: 'Your shopping cart has been emptied'
        }
    },
    
    de: {
        translation: {
            WELCOME_MSG: 'Willkommen in der My Thai Star App. Was kann ich für dich tun? Du kannst die Funktionen der App einsehen indem du "Hilfe" sagst.',
            REQUEST_DISH_MSG: 'Das Gericht, das du angefragt hast ist ',
            PRICE_MSG: 'Der Preis für ',
            IS_MSG: ' ist ',
            EUROS_MSG: ' Euro',
            STATUS_MSG: 'Der Status der Bestellung ',
            SUCCESS_MSG: ' wurde erfolgreich geändert auf ',
            BOOKING_MSG: 'Dein Tisch wurde erfolgreich gebucht.',
            ERROR_BOOKING_MSG: 'Leider ist bei deiner Bestellung ein Fehler aufgetreten. Wurden die Daten für deine Bestellung wirklich korrekt übernommen? Bitte versuche es erneut.',
            ORDER_SUCCESS_MSG: 'Deine Bestellung wurde an das Restaurant übermittelt.',
            NO_MSG: 'nein',
            YES_MSG: 'ja',
            THANK_MSG: 'Ok. Vielen Dank für deine Buchung',
            HELP_MSG: 'Du kannst mich fragen welche Gerichte wir anbieten oder wie viel sie kosten. Du kannst außerdem einen Tisch buchen oder auch Essen bestellen! Kellner können den Inhouse Modus aktivieren oder auch die Tischnummer festlegen. Wie kann ich helfen?',
            GOODBYE_MSG: 'Auf Wiedersehen!',
            ERR_MSG: 'Es tut mir leid. Ich kenne dieses Kommando nicht. Bitte versuche es erneut.',
            REFLECT_MSG: 'Du hast gerade {{intent}} aktiviert',
            PROBLEM_MSG: 'Es tut mir leid. Ich habe Schwierigkeiten das auszuführen, was du verlangt hast. Bitte versuche es erneut.',
            ADD_DISH_MSG: 'Wenn du deiner Bestellung noch etwas hinzufügen möchtest sag einfach "ja". Andernfalls sag "Bestellung absenden"',
            THANK_ORDER_MSG: 'Vielen Dank für deine Bestellung.',
            DISHES_MSG: 'Die verfügbaren Gerichte sind: ',
            BVG_MSG: 'Die verfügbaren Getränke sind: ',
            INHOUSE_ACTIVATED_MSG: 'Der Inhouse Modus wurde aktiviert.',
            DELIVERY_MSG: 'Möchtest du im Restaurant essen oder dein Essen nach Hause geliefert bekommen?',
            DELIVERY_CHOSEN_MSG: 'Deine Wahl wurde gespeichert. Sag "Bestellung abschließen" um den Bestellvorgang zu beenden.',
            BEVERAGE_MSG: 'Das gewählte Getränk wurde deiner Bestellung hinzugefügt.',
            ID_SET_MSG: 'Die Tischnummer wurde vergeben. Die neue Tischnummer ist die ',
            EXTRAS_MSG: 'Es gibt folgende Extras: ',
            ADD_EXTRA_MSG: ' mit extra ',
            CART_MSG: 'Deine Bestellung beinhaltet aktuell ',
            CART_DELETED_MSG: 'Dein Einkaufswagen wurde geleert'
        }
    }
}