export const adminCockpitStub = {
  content: [
    {
      modificationCounter: 1,
      id: 0,
      username: 'james007',
      email: 'admin@mail.com',
      twoFactorStatus: false,
      userRoleId: 3,
    },
    {
      modificationCounter: 1,
      id: 1,
      username: 'manager',
      email: 'manager@mail.com',
      twoFactorStatus: false,
      userRoleId: 2,
    },
    {
      modificationCounter: 1,
      id: 2,
      username: 'waiter',
      email: 'waiter@mail.com',
      twoFactorStatus: false,
      userRoleId: 1,
    },
    {
      modificationCounter: 1,
      id: 3,
      username: 'user0',
      email: 'user0@mail.com',
      twoFactorStatus: false,
      userRoleId: 0,
    },
    {
      modificationCounter: 1,
      id: 4,
      username: 'HansMüller33',
      email: 'Hans.Müller@mail.com',
      twoFactorStatus: false,
      userRoleId: 0,
    },
    {
      modificationCounter: 1,
      id: 5,
      username: 'Lena123',
      email: 'Lena.Weber@mail.com',
      twoFactorStatus: false,
      userRoleId: 0,
    },
    {
      modificationCounter: 1,
      id: 6,
      username: 'SofieS',
      email: 'sweetgirl.sofie@mail.com',
      twoFactorStatus: false,
      userRoleId: 1,
    },
    {
      modificationCounter: 1,
      id: 7,
      username: 'Timboy',
      email: 'timboy@mail.com',
      twoFactorStatus: false,
      userRoleId: 1,
    },
  ],
  pageable: {
    pageNumber: 0,
    pageSize: 1000,
    sort: [],
  },
  totalElements: 13,
};
